### ISSUE TITLE
Chests not spawning with items?

### ISSUE THREAD

**Issue by Bysokar** [timvisee/dungeon-maze#54]
Hi Guys,

Running KCauldron 1.7.10 - cannot get chests to spawn with items at all in any version ?

Is this supposed to happen at all?

**Comment by timvisee** [comment]
Hello,

Thanks for the issue report. No, this should not happen at all (as in, yes the chests should spawn with items in them).

DungeonMaze isn't currently (natively) compatible with KCauldron, but I'll definitely try to fix this problem anyways.

I'll try to take a look into this problem as soon as possible.

Tim Visée

**Comment by DraksterAU** [comment]
Ahh, Awesome @timvisee ! Thanks man :)

**Comment by timvisee** [comment]
Sure, no problem. If you find anything else, please let me know.

About the performance, that might have something to do with the way the plugin stores chunk information. The current version stores data for each chunk in a new file, that's quite expensive performance wise. You know what, I'll try to improve this too, as far as that's possible.

Tim Visée

**Comment by timvisee** [comment]
I'd like to give you an update about a few things.

The chest system has been revised. Chest items are now configurfable, and this should improve in each version when new features are added to the chest configuration system. This configurability will be available in the upcommin Dungeon Maze release. I don't really have a release date planned yet, but I hope I'm able to do this as quickly as possible.

The performance issue has probably something to do with the Minecraft server version you're using. (and not directly because of the new update).I can confirm that at least the latest Spigot versions cause the world generator to be about 8 times slower (or heavier). I assume this is also the case with KCauldron, but I haven't really confirmed this yet. 

I've been working hard on the plugin to get the performance side of the plugin to the top level. I haven't figured out yet what to do about the Spigot (and others) performance problem. I'm working on a few workarounds to get everything working properly again. If I can't directly fix the world generation problem, I'll add some sort of scheduler to the generation system. This will cause chunks to only partially generate at first, but to fully populate over time to spread the server load. (Normally, a whole chunk is generated, and fully populated in an instant).

I'd be happy to know if you have any other notes or bug reports on the latest available Dungeon Maze version.

Tim Visée
